### ISSUE TITLE
incompatibility with phonegap-facebook-plugin.git

### ISSUE THREAD

**Issue by correasebastian** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#140]
I have used many times and the brach.io cordova  plugin and  works fine,
 but in my last project  I have to use  cordova branch.io plugin With http://ngcordova.com/docs/plugins/facebook/  at the same time, and now my project does not compile

when i run `ionic build android` i got this error
`UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:579)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:517)
 FAILED
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_77\bin\java.exe'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 13.249 secs
Error: Error code 1 for command: cmd with args: /s,/c,"D:\sportudo\componentes\kykelyn5fb\platforms\android\gradlew cdvBuildDebug -b D:\sportudo\componentes\kykelyn5fb\platforms\android\build.gradle -Dorg.gradle.daemon=true -Pandroid.useDeprecatedNdk=true"`

i created a github repo where you can see the problem 
https://github.com/correasebastian/kykelyn5fb/

i know is a compatibility issue between this 2 plugins , because i tested the build process with every plugin (isolated) and the build proccess is fine

please review,  many many people use the phonegap facebok plugin, so i could be a massive error

my enviroment info

`Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 1.2.1
Gulp local:
Ionic Version: 1.3.0
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS: Windows 8.1
Node Version: v5.10.1`

**Comment by renesansz** [comment]
Hey @correasebastian , this issue has been resolved, see issue #68.
Closing issue now.
